# Generated by Django 5.0.7 on 2024-07-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefa_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('C', 'Concluída'), ('A', 'Em andamento'), ('P', 'Pendente')], default='P', max_length=1),
        ),
    ]
