# Generated by Django 5.0.7 on 2024-07-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_remove_tarefa_descricao_remove_tarefa_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='fixada',
            field=models.BooleanField(default=False),
        ),
    ]
